version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    # Single container projects
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    # Multi container projects
    # volumes:
    #   - /home/node/app/node_modules
    #   - ./client:/home/node/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev    
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    command: ["npm", "run", "test"]